on:
    workflow_dispatch:

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
        - run: |
            npm install
            npm run build
          working-directory: ./project1
          shell: bash # pwsh,powershell,python
        - run: print %ENV
          shell: perl {0}