name: First WorkFlow
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo " Welcome to our first Github Actions WorFlow "
        
      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: List repository files
        run: ls -la
        
