name: Push PR Workflow
on:
    push:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
    pull_request:
        branches:
            - main
            - "release/**"
        paths:
            - "src/**"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            
            - name: Set up python
              uses: actions/setup-python@v4.6.0
              with:
                    python-version: '3.10'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r src/requirements.txt
            - name: Run tests
              run: |
                python src/test.py

