on:
    schedule:
        - cron: '*/2 * * * *'  # Runs every two minutes
jobs:
    daily-task:
        runs-on: ubuntu-latest
        steps:
            - name: Print Message
              run: echo "This is a scheduled task running every two minutes."

